import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.automationexercise.com/');
  await page.getByText('Home  Products Cart Signup').click();
  await page.goto('https://www.automationexercise.com/login');
  await page.getByPlaceholder('Name').click();
  await page.getByPlaceholder('Name').press('CapsLock');
  await page.getByPlaceholder('Name').fill('R');
  await page.getByPlaceholder('Name').press('CapsLock');
  await page.getByPlaceholder('Name').fill('Rose');
  await page.locator('form').filter({ hasText: 'Signup' }).getByPlaceholder('Email Address').click();
  await page.locator('form').filter({ hasText: 'Signup' }).getByPlaceholder('Email Address').fill('rose1@gmail.com');
  await page.getByRole('button', { name: 'Signup' }).click();
  await page.getByText('Mrs.').click();
  await page.getByLabel('Name *', { exact: true }).click();
  await page.getByLabel('Password *').click();
  await page.getByLabel('Password *').fill('rose1');
  await page.locator('#days').selectOption('4');
  await page.locator('#months').selectOption('10');
  await page.locator('#years').selectOption('2002');
  await page.getByLabel('Sign up for our newsletter!').check();
  await page.locator('#form form div').filter({ hasText: 'Receive special offers from' }).click();
  await page.getByLabel('First name *').click();
  await page.getByLabel('First name *').press('CapsLock');
  await page.getByLabel('First name *').fill('R');
  await page.getByLabel('First name *').press('CapsLock');
  await page.getByLabel('First name *').fill('Rose');
  await page.getByLabel('Last name *').click();
  await page.getByLabel('Last name *').press('CapsLock');
  await page.getByLabel('Last name *').fill('O');
  await page.getByLabel('Last name *').press('CapsLock');
  await page.getByLabel('Last name *').fill('One');
  await page.getByLabel('Company', { exact: true }).click();
  await page.getByLabel('Company', { exact: true }).press('CapsLock');
  await page.getByLabel('Company', { exact: true }).fill('B');
  await page.getByLabel('Company', { exact: true }).press('CapsLock');
  await page.getByLabel('Company', { exact: true }).fill('Billon ');
  await page.getByLabel('Company', { exact: true }).press('CapsLock');
  await page.getByLabel('Company', { exact: true }).fill('Billon T');
  await page.getByLabel('Company', { exact: true }).press('CapsLock');
  await page.getByLabel('Company', { exact: true }).fill('Billon Tech');
  await page.getByLabel('Address * (Street address, P.').click();
  await page.getByLabel('Address * (Street address, P.').fill('gevh behdg');
  await page.getByLabel('Address 2').click();
  await page.getByLabel('Address 2').fill('asdf ghk');
  await page.getByLabel('Country *').selectOption('Israel');
  await page.getByLabel('State *').click();
  await page.getByLabel('State *').fill('new mess');
  await page.locator('p').filter({ hasText: 'City *' }).click();
  await page.getByLabel('City *').fill('lamptwon');
  await page.locator('#zipcode').click();
  await page.locator('#zipcode').fill('12341');
  await page.getByLabel('Mobile Number *').click();
  await page.getByLabel('Mobile Number *').fill('077283746');
  await page.getByRole('button', { name: 'Create Account' }).click();
  await page.getByText('Account Created!').click();
  await page.getByRole('link', { name: 'Continue' }).click();
  await page.getByText('Logged in as Rose').click();
  await page.locator('div:nth-child(6) > .product-image-wrapper > .single-products > .product-overlay > .overlay-content > .btn').click();
  await page.getByRole('button', { name: 'Continue Shopping' }).click();
  await page.locator('div:nth-child(7) > .product-image-wrapper > .single-products > .productinfo > .btn').click();
  await page.getByRole('button', { name: 'Continue Shopping' }).click();
  await page.getByRole('link', { name: ' Cart' }).click();
  await page.getByText('Shopping Cart').click();
  await page.getByText('Proceed To Checkout').click();
  await page.getByRole('heading', { name: 'Address Details' }).click();
  await page.getByText('Your delivery address Mrs.').click();
  await page.getByRole('heading', { name: 'Review Your Order' }).click();
  await page.getByRole('cell', { name: 'Item' }).click();
  await page.getByRole('cell', { name: 'Description' }).click();
  await page.getByRole('cell', { name: 'Price' }).click();
  await page.getByRole('cell', { name: 'Quantity' }).click();
  await page.getByRole('cell', { name: 'Total', exact: true }).click();
  await page.getByRole('cell', { name: 'Total Amount' }).click();
  await page.getByText('Rs. 2100').click();
  await page.getByRole('link', { name: 'Place Order' }).click();
  await page.locator('input[name="name_on_card"]').click();
  await page.locator('input[name="name_on_card"]').fill('09876543');
  await page.locator('input[name="card_number"]').click();
  await page.locator('input[name="card_number"]').fill('67890876');
  await page.getByPlaceholder('ex.').click();
  await page.getByPlaceholder('ex.').fill('657');
  await page.getByPlaceholder('MM').click();
  await page.getByPlaceholder('MM').fill('35');
  await page.getByPlaceholder('YYYY').click();
  await page.getByPlaceholder('YYYY').fill('0987');
  await page.getByRole('button', { name: 'Pay and Confirm Order' }).click();
  await page.getByText('Order Placed!').click();
  await page.getByText('Congratulations! Your order').click();
  await page.getByRole('link', { name: ' Delete Account' }).click();
  await page.getByText('Account Deleted!').click();
  await page.getByRole('link', { name: 'Continue' }).click();
});