import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.automationexercise.com/');
  await page.getByRole('link', { name: ' Signup / Login' }).click();
  await page.getByPlaceholder('Name').click();
  await page.getByPlaceholder('Name').press('CapsLock');
  await page.getByPlaceholder('Name').fill('B');
  await page.getByPlaceholder('Name').press('CapsLock');
  await page.getByPlaceholder('Name').fill('Bob ');
  await page.getByPlaceholder('Name').press('CapsLock');
  await page.getByPlaceholder('Name').fill('Bob B');
  await page.getByPlaceholder('Name').press('CapsLock');
  await page.getByPlaceholder('Name').fill('Bob Brown');
  await page.locator('form').filter({ hasText: 'Signup' }).getByPlaceholder('Email Address').click();
  await page.locator('form').filter({ hasText: 'Signup' }).getByPlaceholder('Email Address').fill('bobbrown@gmail.com');
  await page.getByRole('button', { name: 'Signup' }).click();
  await page.getByLabel('Mrs.').check();
  await page.getByLabel('Password *').click();
  await page.getByLabel('Password *').press('CapsLock');
  await page.getByLabel('Password *').fill('B');
  await page.getByLabel('Password *').press('CapsLock');
  await page.getByLabel('Password *').fill('Bobbrown123');
  await page.locator('#days').selectOption('18');
  await page.locator('#months').selectOption('9');
  await page.locator('#years').selectOption('1999');
  await page.getByLabel('Sign up for our newsletter!').check();
  await page.getByLabel('Receive special offers from').check();
  await page.getByLabel('First name *').click();
  await page.getByLabel('First name *').press('CapsLock');
  await page.getByLabel('First name *').fill('B');
  await page.getByLabel('First name *').press('CapsLock');
  await page.getByLabel('First name *').fill('Bob');
  await page.getByLabel('Last name *').click();
  await page.getByLabel('Last name *').press('CapsLock');
  await page.getByLabel('Last name *').fill('B');
  await page.getByLabel('Last name *').press('CapsLock');
  await page.getByLabel('Last name *').fill('Brown');
  await page.getByLabel('Company', { exact: true }).click();
  await page.getByLabel('Company', { exact: true }).press('CapsLock');
  await page.getByLabel('Company', { exact: true }).fill('S');
  await page.getByLabel('Company', { exact: true }).press('CapsLock');
  await page.getByLabel('Company', { exact: true }).fill('Sysco ');
  await page.getByLabel('Company', { exact: true }).press('CapsLock');
  await page.getByLabel('Company', { exact: true }).fill('Sysco L');
  await page.getByLabel('Company', { exact: true }).press('CapsLock');
  await page.getByLabel('Company', { exact: true }).fill('Sysco Labs');
  await page.getByLabel('Address * (Street address, P.').click();
  await page.getByLabel('Address * (Street address, P.').press('CapsLock');
  await page.getByLabel('Address * (Street address, P.').fill('R');
  await page.getByLabel('Address * (Street address, P.').press('CapsLock');
  await page.getByLabel('Address * (Street address, P.').fill('Royal ');
  await page.getByLabel('Address * (Street address, P.').press('CapsLock');
  await page.getByLabel('Address * (Street address, P.').fill('Royal A');
  await page.getByLabel('Address * (Street address, P.').press('CapsLock');
  await page.getByLabel('Address * (Street address, P.').fill('Royal Arcade');
  await page.getByLabel('Address 2').click();
  await page.getByLabel('Address 2').press('CapsLock');
  await page.getByLabel('Address 2').fill('C');
  await page.getByLabel('Address 2').press('CapsLock');
  await page.getByLabel('Address 2').fill('Colombo ');
  await page.getByLabel('Country *').selectOption('Canada');
  await page.getByLabel('State *').click();
  await page.getByLabel('State *').fill('1234');
  await page.getByLabel('City *').click();
  await page.getByLabel('City *').press('CapsLock');
  await page.getByLabel('City *').fill('K');
  await page.getByLabel('City *').press('CapsLock');
  await page.getByLabel('City *').fill('Kotte');
  await page.locator('#zipcode').click();
  await page.locator('#zipcode').fill('12345');
  await page.getByLabel('Mobile Number *').click();
  await page.getByLabel('Mobile Number *').fill('0772342321');
  await page.getByRole('button', { name: 'Create Account' }).click();
  await page.getByRole('link', { name: 'Continue' }).click();
  await page.getByText('Logged in as Bob Brown').click();
  await page.locator('li').filter({ hasText: 'Delete Account' }).click();
  await page.getByRole('link', { name: 'Continue' }).click();
});