import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://automationexercise.com/');
  await page.getByText('Home  Products Cart Signup').click();
  await page.getByRole('link', { name: ' Signup / Login' }).click();
  await page.locator('form').filter({ hasText: 'Login' }).getByPlaceholder('Email Address').click();
  await page.locator('form').filter({ hasText: 'Login' }).getByPlaceholder('Email Address').fill('roy123@gmail.com');
  await page.getByPlaceholder('Password').click();
  await page.getByPlaceholder('Password').press('CapsLock');
  await page.getByPlaceholder('Password').press('CapsLock');
  await page.getByPlaceholder('Password').fill('roy123');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByText('Logged in as Roy').click();
  await page.locator('div:nth-child(7) > .product-image-wrapper > .single-products > .productinfo > .btn').click();
  await page.getByRole('button', { name: 'Continue Shopping' }).click();
  await page.locator('div:nth-child(9) > .product-image-wrapper > .single-products > .productinfo > .btn').click();
  await page.getByRole('button', { name: 'Continue Shopping' }).click();
  await page.getByRole('link', { name: ' Cart' }).click();
  await page.getByText('Shopping Cart').click();
  await page.getByText('Proceed To Checkout').click();
  await page.getByRole('heading', { name: 'Address Details' }).click();
  await page.getByRole('heading', { name: 'Your delivery address' }).click();
  await page.getByRole('heading', { name: 'Review Your Order' }).click();
  await page.getByRole('cell', { name: 'Item' }).click();
  await page.getByRole('cell', { name: 'Description' }).click();
  await page.getByRole('cell', { name: 'Price' }).click();
  await page.getByRole('cell', { name: 'Quantity' }).click();
  await page.getByRole('cell', { name: 'Total', exact: true }).click();
  await page.getByText('Total Amount').click();
  await page.locator('textarea[name="message"]').click();
  await page.locator('textarea[name="message"]').press('CapsLock');
  await page.locator('textarea[name="message"]').fill('T');
  await page.locator('textarea[name="message"]').press('CapsLock');
  await page.locator('textarea[name="message"]').fill('Testing 234');
  await page.getByRole('link', { name: 'Place Order' }).click();
  await page.locator('input[name="name_on_card"]').click();
  await page.locator('input[name="name_on_card"]').fill('qwerty rtyui');
  await page.locator('input[name="card_number"]').click();
  await page.locator('input[name="card_number"]').fill('12345678');
  await page.getByPlaceholder('ex.').click();
  await page.getByPlaceholder('ex.').fill('789');
  await page.getByPlaceholder('MM').click();
  await page.getByPlaceholder('MM').fill('98');
  await page.getByPlaceholder('YYYY').click();
  await page.getByPlaceholder('YYYY').fill('3456');
  await page.getByRole('button', { name: 'Pay and Confirm Order' }).click();
  await page.getByText('Order Placed!').click();
  await page.getByText('Congratulations! Your order').click();
});