import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://automationexercise.com/');
  await page.locator('div').filter({ hasText: 'Home  Products Cart Signup' }).nth(2).click();
  await page.getByRole('link', { name: ' Signup / Login' }).click();
  await page.getByPlaceholder('Name').click();
  await page.getByPlaceholder('Name').press('CapsLock');
  await page.getByPlaceholder('Name').fill('N');
  await page.getByPlaceholder('Name').press('CapsLock');
  await page.getByPlaceholder('Name').fill('Net');
  await page.locator('form').filter({ hasText: 'Signup' }).getByPlaceholder('Email Address').click();
  await page.locator('form').filter({ hasText: 'Signup' }).getByPlaceholder('Email Address').fill('net@gmail.com');
  await page.getByRole('button', { name: 'Signup' }).click();
  await page.getByLabel('Mr.').check();
  await page.getByLabel('Password *').click();
  await page.getByLabel('Password *').fill('net@gmail');
  await page.locator('#days').selectOption('20');
  await page.locator('#months').selectOption('4');
  await page.locator('#years').selectOption('2009');
  await page.getByLabel('Sign up for our newsletter!').check();
  await page.getByLabel('Receive special offers from').check();
  await page.getByLabel('First name *').click();
  await page.getByLabel('First name *').press('CapsLock');
  await page.getByLabel('First name *').fill('N');
  await page.getByLabel('First name *').press('CapsLock');
  await page.getByLabel('First name *').fill('Net');
  await page.getByLabel('Last name *').click();
  await page.getByLabel('Last name *').press('CapsLock');
  await page.getByLabel('Last name *').fill('N');
  await page.getByLabel('Last name *').press('CapsLock');
  await page.getByLabel('Last name *').fill('Net');
  await page.getByLabel('Company', { exact: true }).click();
  await page.getByLabel('Company', { exact: true }).press('CapsLock');
  await page.getByLabel('Company', { exact: true }).fill('N');
  await page.getByLabel('Company', { exact: true }).press('CapsLock');
  await page.getByLabel('Company', { exact: true }).fill('Net ');
  await page.getByLabel('Company', { exact: true }).press('CapsLock');
  await page.getByLabel('Company', { exact: true }).fill('Net N');
  await page.getByLabel('Company', { exact: true }).press('CapsLock');
  await page.getByLabel('Company', { exact: true }).fill('Net Net ');
  await page.getByLabel('Company', { exact: true }).press('CapsLock');
  await page.getByLabel('Company', { exact: true }).fill('Net Net N');
  await page.getByLabel('Company', { exact: true }).press('CapsLock');
  await page.getByLabel('Company', { exact: true }).fill('Net Net Net ');
  await page.getByLabel('Address * (Street address, P.').click();
  await page.getByLabel('Address * (Street address, P.').press('CapsLock');
  await page.getByLabel('Address * (Street address, P.').fill('N');
  await page.getByLabel('Address * (Street address, P.').press('CapsLock');
  await page.getByLabel('Address * (Street address, P.').fill('Net ');
  await page.getByLabel('Address * (Street address, P.').press('CapsLock');
  await page.getByLabel('Address * (Street address, P.').fill('Net N');
  await page.getByLabel('Address * (Street address, P.').press('CapsLock');
  await page.getByLabel('Address * (Street address, P.').fill('Net Net ');
  await page.getByLabel('Address * (Street address, P.').press('CapsLock');
  await page.getByLabel('Address * (Street address, P.').fill('Net Net N');
  await page.getByLabel('Address * (Street address, P.').press('CapsLock');
  await page.getByLabel('Address * (Street address, P.').fill('Net Net Net ');
  await page.getByLabel('Address 2').click();
  await page.getByLabel('Address 2').press('CapsLock');
  await page.getByLabel('Address 2').fill('N');
  await page.getByLabel('Address 2').press('CapsLock');
  await page.getByLabel('Address 2').fill('Net ');
  await page.getByLabel('Address 2').press('CapsLock');
  await page.getByLabel('Address 2').fill('Net N');
  await page.getByLabel('Address 2').press('CapsLock');
  await page.getByLabel('Address 2').fill('Net Net ');
  await page.getByLabel('Address 2').press('CapsLock');
  await page.getByLabel('Address 2').fill('Net Net N');
  await page.getByLabel('Address 2').press('CapsLock');
  await page.getByLabel('Address 2').fill('Net Net Net');
  await page.getByLabel('Country *').selectOption('United States');
  await page.getByLabel('State *').click();
  await page.getByLabel('State *').press('CapsLock');
  await page.getByLabel('State *').fill('N');
  await page.getByLabel('State *').press('CapsLock');
  await page.getByLabel('State *').fill('Net ');
  await page.getByLabel('State *').press('CapsLock');
  await page.getByLabel('State *').fill('Net N');
  await page.getByLabel('State *').press('CapsLock');
  await page.getByLabel('State *').fill('Net Net ');
  await page.getByLabel('State *').press('CapsLock');
  await page.getByLabel('State *').fill('Net Net N');
  await page.getByLabel('State *').press('CapsLock');
  await page.getByLabel('State *').fill('Net Net Net ');
  await page.getByLabel('City *').click();
  await page.getByLabel('City *').press('CapsLock');
  await page.getByLabel('City *').fill('N');
  await page.getByLabel('City *').press('CapsLock');
  await page.getByLabel('City *').fill('Net ');
  await page.locator('#zipcode').click();
  await page.locator('#zipcode').fill('net 123');
  await page.getByLabel('Mobile Number *').click();
  await page.getByLabel('Mobile Number *').fill('0982837465');
  await page.getByRole('button', { name: 'Create Account' }).click();
  await page.getByText('Account Created!').click();
  await page.getByRole('link', { name: 'Continue' }).click();
  await page.getByText('Logged in as Net').click();
  await page.locator('.productinfo > .btn').first().click();
  await page.getByRole('button', { name: 'Continue Shopping' }).click();
  await page.getByRole('link', { name: ' Cart' }).click();
  await page.getByText('Shopping Cart').click();
  await page.getByText('Proceed To Checkout').click();
  await page.getByText('Your delivery address Mr. Net').click();
  await page.locator('#address_delivery').getByText('Mr. Net Net').click();
  await page.locator('#address_delivery').getByText('Net Net Net').first().click();
  await page.locator('#address_delivery').getByText('Net Net Net').nth(1).click();
  await page.locator('#address_delivery li').filter({ hasText: /^Net Net Net$/ }).click();
  await page.locator('#address_delivery').getByText('Net Net Net Net net').click();
  await page.locator('#address_delivery').getByText('United States').click();
  await page.locator('#address_delivery').getByText('0982837465').click();
  await page.getByText('Your billing address Mr. Net').click();
  await page.getByRole('heading', { name: 'Your billing address' }).click();
  await page.locator('#address_invoice').getByText('Mr. Net Net').click();
  await page.locator('#address_invoice').getByText('Net Net Net').first().click();
  await page.locator('#address_invoice').getByText('Net Net Net').nth(1).click();
  await page.locator('#address_invoice li').filter({ hasText: /^Net Net Net$/ }).click();
  await page.locator('#address_invoice').getByText('Net Net Net Net net').click();
  await page.locator('#address_invoice').getByText('United States').click();
  await page.locator('#address_invoice').getByText('0982837465').click();
  await page.getByRole('link', { name: 'Place Order' }).click();
  await page.getByRole('link', { name: ' Delete Account' }).click();
  await page.getByText('Account Deleted!').click();
  await page.getByRole('link', { name: 'Continue' }).click();
});